config/routes.rb
ExpenseManager::Application.routes.draw do

  devise_for :users

  resources :users, only: :show
  resources :groups

  root to: "home#index", via: 'get'

end

app/models/contribution.rb
class Contribution
  include Mongoid::Document

  embedded_in :group
end

app/models/group.rb
class Group
  include Mongoid::Document
  field :name
  field :owner_id, type: BSON::ObjectId
  field :admin_ids, type: Array
  field :contributor_ids, type: Array
  validates_presence_of :name
  validates_uniqueness_of :name, case_sensitive: false
  attr_accessible :name

  after_destroy do
    self.users.each do |user|
      if user.group_ids.include? self.id
        user.remove_group self, false
      end
    end
  end

  def isSafeToLeave? user
    !user.isOwner? self
  end

  def remove_user user, continue = true
    self.user_ids.delete user.id
    self.save
    if continue
      user.remove_group self, false
    end
    true
  end

  def owner
    User.find(self.owner_id)
  end

  def owner= user
    case user
    when User
      self.owner_id = user.id
    when BSON::ObjectId
      self.owner_id = User.find(user).id
    when String
      self.owner_id = User.find(user).id if BSON::ObjectId.legal? user
    end
    self.save
  end

  def admins
    unless self.admin_ids.empty?
      User.find(self.admin_ids)
    else
      []
    end
  end

  # This method replaces the existing admin_ids Array. To add an Admin without
  # removing the others, use pushAdmins
  def admins= users
    case users
    when User
      self.admin_ids = [users.id]
    when BSON::ObjectId
      self.admin_ids = [User.find(users).id]
    when String
      self.admin_ids = [User.find(users).id] if BSON::ObjectId.legal? users
    when Array
      self.admin_ids = []
      users.each do |user|
        self.pushAdmins user
      end
    end
  end

  # This method and admins= are left deliberately inefficient to facilitate
  # checking that every user passed into admin_ids is a valid user. It is also
  # expected that setting the admin array is something that will be done
  # infrequently and with a relatively small array
  def pushAdmins users
    case users
    when User
      self.admin_ids << users.id
    when BSON::ObjectId
      self.admin_ids << User.find(users).id
    when String
      self.admin_ids << User.find(users).id if BSON::ObjectId.legal? users
    when Array
      users.each do |user|
        self.pushAdmins user
      end
    end
  end

  def removeAdmins users
    case users
    when User
      self.admin_ids.delete users.id
    when BSON::ObjectId
      self.admin_ids.delete User.find(users).id
    when String
      self.admin_ids.delete User.find(users).id if BSON::ObjectId.legal? users
    when Array
      users.each do |user|
        self.removeAdmins user
      end
    end
  end

  has_and_belongs_to_many :users
  embeds_many :contributions
end

app/models/payment.rb
class Payment < Contribution
  include Mongoid::Document
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  field :first_name
  field :last_name
  field :user_name
  field :email
  validates_presence_of :first_name, :last_name, :user_name
  validates_uniqueness_of :user_name, :email, :case_sensitive => false
  attr_accessible(:user_name, :email, :password, :password_confirmation,
                  :remember_me, :first_name, :last_name)

  def remove_group group, continue = true
    self.group_ids.delete group.id
    self.save
    if continue
      group.remove_user self, false
    end
  end

  def isOwner? group
    self == group.owner
  end

  def isAdmin? group
    self == group.owner || group.admin_ids.include?(self.id)
  end

  def isMember? group
    self.in? group.users
  end

  def getFullName
    "#{self.first_name.capitalize} #{self.last_name.capitalize}"
  end

  has_and_belongs_to_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    user = current_user
    group = user.groups.create!(params[:group])
    group.owner = user.id
    group.admin_ids = []
    group.save
    redirect_to group
  end

  def edit
    @group = Group.find(params[:id])

    if  current_user.isAdmin? @group
      @ownerSelect = [[@group.owner.getFullName, @group.owner.id]]
      @group.users.each do |user|
         @ownerSelect.push ([user.getFullName, user.id])
      end
      @ownerSelect.uniq!

      @userSelect = {}
      (@group.users - [@group.owner]).each do |user|
        @userSelect[user.getFullName] = user.id
      end

    else
      flash[:alert] = I18n.t "group.failure.edit"
      redirect_to @group
    end
  end

  def update
    group = Group.find(params[:id])
    if params[:join]
      group.users << current_user
    elsif params[:leave]
      leave_group group
    elsif current_user.isAdmin? group
      update_group group, params[:group]
    else
      flash[:alert] = I18n.t "group.failure.edit"
    end
    redirect_to group
  end

  def destroy
    group = Group.find(params[:id])
    if current_user.isOwner? group
      group.destroy
    else
      flash[:alert] = I18n.t "group.failure.destroy"
    end
    redirect_to root_path
  end

  private

  def leave_group group
    if group.isSafeToLeave? current_user
      current_user.remove_group group
    else
      flash[:alert] = I18n.t("group.failure.is_owner")
    end
  end

  def update_group group, new_data
    note = nil
    # logger.debug new_data[:admin_ids].class is an Array

    group.name = new_data[:name] unless new_data[:name].blank?

    if params[:own_ok] == "1" && current_user.isOwner?(group)
      group.owner = new_data[:owner_id]
      note = "owner"
    end

    if current_user.isOwner?(group) && params[:adm_ok] == "1"
      group.admins = new_data[:admins]
      note ||= "admin"
    end

    if current_user.isAdmin?(group) && params[:usr_ok] == "1"
      user = ""
      user = User.find(new_data[:user_ids]) if BSON::ObjectId.legal? new_data[:user_ids]
      logger.debug user.inspect
      unless user.in? group.admins
        success = group.remove_user user
        note ||= "kicked" if success
      else
        flash[:alert] = I18n.t "group.failure.kick_admin"
      end
    end

#    unless (params[:own_ok] == "1") && current_user.isOwner?(group)
#      new_data.delete :owner_id
#    else
#      user = User.find new_data[:owner_id]
#      group.admin_ids.push(user.id).uniq!
#      note = "owner"
#    end
#    group.attributes = new_data
    group.save
    note ||= "success" if flash[:alert].nil?
    flash[:notice] = I18n.t "group.edit.#{note}" unless note.blank?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def show
   @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  #def getFullName user
  #  unless user.blank?
  #    user.getFullName
  #  else
  #    nil
  #  end
  #end

  def userLink user
    link_to user.getFullName, user
  end

  def greeting user
    unless user.blank?
      "Hello, #{current_user.getFullName}!"
    else
      "Hello!"
    end
  end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/groups/_admins.html.haml
%div
  - unless @group.admins.empty?
    The group administrators are:
    - num = 0
    - @group.admins.each do |admin|
      %p
        #{num += 1}.
        = userLink admin
  -else
    This group has no administrators.

app/views/groups/_form.html.haml
= f.inputs do
  - if current_user.isOwner? group
    =f.input :name
    = f.input(:owner_id, as: :select, collection: @ownerSelect, include_blank: false)
    %span.confirm
      = check_box_tag :own_ok
      = label_tag :own_ok, "Confirm change of owner."

    #admin_edit
      %h3 Edit Administrator Roles
      - unless @userSelect.empty?
        = f.input(:admins, as: :check_boxes, collection: @userSelect, label: "Admins", hidden_fields: false)
        %span.confirm
          = check_box_tag :adm_ok
          = label_tag :adm_ok, "Confirm change of admins."
      - else
        = I18n.t "group.failure.no_users"

  = f.input(:user_ids, as: :select, collection: @userSelect, label: "Remove User", selected: "", disabled: [current_user.id])
  %span.confirm
    = check_box_tag :usr_ok
    = label_tag :usr_ok, "Confirm removal of user."

app/views/groups/_old_form.html.haml
%p
  =f.label :name
  %br/
  =f.text_field :name

- if current_user.isOwner? group
  %p
    =f.label :owner
    %br/
    =f.select :owner_id, @ownerSelect
    =check_box_tag :own_ok
    =label_tag :own_ok, "Click to confirm change of owner."

  #admin_edit
    %h4 Edit Administrator Roles
    %br/
    %table
      %tr
        %th User
        %th Admin?

      - for user in @adminSelect
        %tr
          %td= user.getFullName
          %td= f.check_box 'admin_ids', {name: 'group[admin_ids][]'}, user.id
    %br/
    =check_box_tag :adm_ok
    =label_tag :adm_ok, "Click to confirm change of admins"

app/views/groups/_user_controls.html.haml
- if !current_user.isMember? @group
  = link_to "Join this Group!", group_path(join: true), method: :put
-else
  = link_to "Leave this Group", group_path(leave: true), :confirm => "Are you sure?", method: :put

%br
- if (current_user.isAdmin?(@group) || current_user.isOwner?(@group))
  =link_to "Edit this Group", edit_group_path

app/views/groups/edit.html.haml
%h2 Edit #{@group.name}

= semantic_form_for(@group, as: :group, url: {action: "update"}) do |f|
  = render "form", group: @group, f: f
  = f.buttons do
    %p= f.commit_button label: "Update"

-if current_user.isOwner? @group
  %p Unhappy? #{link_to "Delete this Group", group_path, :confirm => "Are you sure?", :method => :delete}.

= link_to "Back", :back

app/views/groups/index.html.haml
%h1 Groups Homepage

%h3 This is a list of all current groups

- num = 0
- @groups.each do |group|
  %p
    #{num +=1}.
    = link_to group.name, group

app/views/groups/new.html.haml
%h2 New Group

= form_for(@group, as: :group, url: {action: "create"}) do |f|
  %p
    = f.label :name
    %br/
    = f.text_field :name

  %p= f.submit "New Group"

app/views/groups/show.html.haml
%h1 #{@group.name} Main Page

%h4 This group's owner is #{userLink(@group.owner)}

= render "admins"

%br/

%div
  The group members are:
  - num = 0
  - @group.users.each do |user|
    %p
      #{num += 1}.
      = userLink user

= render "user_controls"

app/views/home/index.html.haml
%h1 Expense Manager Homepage!

%p
  Welcome to my new app! This is only a placeholder for now but I'll be adding
  new functionality soon!


%h3 This is a list of all the users currently signed up:

- num = 0
- @users.each do |user|
  %p
    #{num +=1}.
    = userLink user

app/views/layouts/_header.html.haml
%header
  %nav
    %h4= greeting current_user
    %ul.hmenu
      = render 'devise/menu/registration_items'
      = render 'devise/menu/login_items'
    %ul.hmenu
      %li= link_to "Home", root_path
      %li= link_to "Groups", groups_path

app/views/layouts/_stylesheets.html.haml
<!--[if lt IE 9]
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
![endif]-->
<!--[if lt IE8]]
= stylesheet_link_tag 'blueprint/ie'
![endif]-->
<!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
<!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

= stylesheet_link_tag "application"
= stylesheet_link_tag 'blueprint/print', media: 'print'
= javascript_include_tag "application"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ExpenseManager
    = render "/layouts/stylesheets"
    = csrf_meta_tags
  %body
    .container
      = render  "/layouts/header"

      %section.round
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
        = yield

app/views/users/show.html.haml
%h1 #{@user.getFullName}'s Profile

- if @user.id == current_user.id
  %div This is you!


%h3 #{@user.first_name.capitalize} is a member of these groups:

-num = 0
- @user.groups.each do |group|
  %p
    #{num += 1}.
    = link_to group.name, group
    - if @user.isOwner? group
      (Owner)
    - elsif @user.isAdmin? group
      (Admin)

%p= link_to "Create a new Group!", new_group_path